### ISSUE TITLE
Class 'App\Http\Controllers\Imgur' not found

### ISSUE THREAD

**Issue by chinmay235** [Mombuyish/Laravel-Imgur#1]
I am totally new in Laravel. I just started one gallery project. I want to store my image in imgur.com site. I followed and successfully implemented. While I run my project I got this error message:

```
 Imgur::upload(my_image_url);
```
Error:
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'App\Http\Controllers\Imgur' not found
```

Please help

**Comment by Mombuyish** [comment]
Hi, you should use Imgur on your controller

``` php
<?php

namespace App\Http\Controllers;

use Imgur;
...
```

by the way, make sure you have been alias facade in app.php.

**Comment by chinmay235** [comment]
Hi Yish,
Thanks for your reply. I am New in this framework so getting little bit
problem. You are really ginious. Let me  check and confirm you soon. If I'm
getting any this related issue. I need your help. May be I disturb you
sometimes over mail.

Thanks
Chinmay Kumar Sahu

**Comment by chinmay235** [comment]
Hi @Mombuyish, Your code working fine. But I have 2 doubt.

1. How could I upload directly from browse file to imgur server? Could you please check below I am directly passing the URL path. This is working fine for me. I want browse file instead of URL . Is it possible?
2. I have successfully inserted my image to imgur site. When I check my imgur account. That image is not exist. Could you please help me and let me know where that images are going.
```
$image = Imgur::upload('https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1200px-Apple_logo_black.svg.png');
echo $image->link(); exit;
```

Thanks
Chinmay

**Comment by Mombuyish** [comment]
Hi,
you can read documentation to use.
https://github.com/Mombuyish/Laravel-Imgur#usage

your file must instance of `Illuminate\Http\UploadedFile` and check your imgur api token is working.

maybe you can use `dd()` (die and dump) to check out your concrete.

thanks.

**Comment by chinmay235** [comment]
Hi @Mombuyish,
Thanks for reply. 

My API token is working fine. And file uploaded successfully. But That file not exist in my account.
Ok let me try once.

Thanks.

**Comment by chinmay235** [comment]
Hi,
Sorry for late reply.
I saw my key is working fine. But don't know where my all images store.
I logged in my imgur.com which linked with my website. There are no any
images which I was uploading through my web page.

Thanks.

Thanks
Chinmay Kumar Sahu

**Comment by chinmay235** [comment]
Instead of Client ID I am using AccessToken Now It's working fine.
