### ISSUE TITLE
Ability to change URL

### ISSUE THREAD

**Issue by AbminDev** [Mombuyish/Laravel-Imgur#2]
I use the Imgur API for commercial purposes, and for this I need to send requests not here `https://api.imgur.com/` but here `https://imgur-apiv3.p.rapidapi.com/`.

This is from the official Imgur API documentation:

> To use Imgur's API commercially, you must first register your application. Once that's done, you must register with RapidAPI. RapidAPI allows you to choose a pricing plan that fits your needs. From then on, the API endpoint is https://imgur-apiv3.p.rapidapi.com/ which must be used in place of https://api.imgur.com/. Additionally, you must set a X-Mashape-Key request header with the key obtained from RapidAPI.

I suggest adding the ability to replace the URL in the .env file.

**Comment by Mombuyish** [comment]
Thanks! 1.1.0 41d9fc8604edd6
