### ISSUE TITLE
Image upload don't work

### ISSUE THREAD

**Issue by AbminDev** [Mombuyish/Laravel-Imgur#3]
In file Upload.php 33 line:
`$this->url = $endpoint;`
replace to
`$this->endpoint = $endpoint;`

But somewhere else there is a problem, please check your code

**Comment by Mombuyish** [comment]
Delete your `config/imgur.php` and republish, set it in `.env` it should be work.

**Comment by AbminDev** [comment]
I do not have such a file

**Comment by AbminDev** [comment]
Thank you, after `php artisan vendor:publish` my code is working
