### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by RohitM-IN** [Mombuyish/Laravel-Imgur#4]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - yish/imgur 1.1.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for yish/imgur ^1.1 -> satisfiable by yish/imgur[1.1.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by Mombuyish** [comment]
WIP, Thanks.

**Comment by Mombuyish** [comment]
Hi, the problem has been solved.

if you're using previously <= laravel 7 -> `1.1.x`
laravel 8 and later -> `2.x`

cheers.
